Document installation onto NVMe feature
home-assistant/yellow.home-assistant.io pull request #141
Opened 2023-04-05 15:44 UTC by agners

This feature is supported with the latest Home Assistant OS Installer for Yellow (see https://github.com/NabuCasa/yellow-buildroot/releases/tag/yellow-installer-20230405 and https://github.com/home-assistant/version/pull/285).

2023-04-05 17:17 UTC, c0ffeeca7 approved these changes

2023-04-05 17:17 UTC, c0ffeeca7 commented on src/procedures/procedures.11tydata.yaml
> +          <li class="info">Advanced: Home Assistant OS is installed onto the eMMC if available on your CM4. If you
```suggestion
          <li class="info"><b>Advanced</b>: Installing the Home Assistant OS onto the NVMe SSD: </br> By default, Home Assistant OS is installed onto the eMMC. Unless you have a CM4 Lite, which does not have an eMMC. If you 
```

2023-04-06 06:48 UTC, c0ffeeca7 requested changes
maybe we could give a bit more context there

2023-04-06 06:58 UTC, agners commented
> maybe we could give a bit more context there

What do you mean exactly?

The context should be largely given: OS installation while using the NVMe (as this is what this guide is about).

2023-04-06 07:02 UTC, c0ffeeca7 commented
> > maybe we could give a bit more context there
> 
> What do you mean exactly?
> 
> The context should be largely given: OS installation while using the NVMe (as this is what this guide is about).

I was talking about the sentence I rephrased. That's all :-)

2023-04-06 07:52 UTC, c0ffeeca7 approved these changes

2023-04-06 07:52 UTC, merged